core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('allauth.urls')),
    path('dashboard/', include('user.urls')),
    path('', include('surveys.urls')),

]

surveys/urls.py
from django.urls import path
from .views import *

app_name = 'surveys'

urlpatterns = [
    path('', home, name='home'),
    path('survey/<slug:slug>/', passSurvey, name='passSurvey'),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
    path('my-surveys/', mySurveys, name='mySurveys'),
    path('create-survey/', createSurvey, name='createSurvey'),
    path('survey-responses/<slug:slug>/', surveyResponses, name='surveyResponses'),
    path('survey-response/<slug:slug>/<int:response_id>/', surveyResponse, name='surveyResponse'),
]

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - {{title}}</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/tailwind.js' %}"></script>
    {% block headScripts %}{% endblock headScripts %}
</head>
<body>

    {% include 'dashboard/partials/header.html' %}

    {% comment %} container to contain sidebar and  {% endcomment %}
    <div class="flex flex-row">
        <div class="w-1/6">
            {% include 'dashboard/partials/nav.html' %}
        </div>
        <div class="container mx-auto w-5/6 p-4">
            <h1 class="text-2xl font-bold mb-6">{{title}}</h1>
            {% block content %}{% endblock content %}
        </div>
    </div>

    {% include 'dashboard/partials/footer.html' %}

    {% block bodyScripts %}{% endblock bodyScripts %}
    
</body>

{% block endScripts %}{% endblock endScripts %}

</html>

templates/dashboard/createSurvey.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block content %}
    
    <div class="container p-4">
        <div id="error_container">
            
        </div>

        <form method="post" id="create_survey_form" class="w-full max-w-lg">
            {% csrf_token %}
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                  <label for="id_survey_title" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" >
                      Title of the survey
                  </label>
                  <input name="survey_title" id="id_survey_title" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="text">
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                  <label for="id_survey_description" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" >
                    Description of the survey
                  </label>
                  <textarea name="survey_description" id="id_survey_description" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" ></textarea>
                </div>
            </div>

            <div id="questions" class="p-4 rounded border border-gray-200">
                <h4 class="text-gray-700 text-lg font-bold mb-2 questions-title hidden">Questions:</h4>

                <div class="question_1">
            
                    <div class="flex flex-wrap -mx-3 mb-2">
        
                        <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
        
                          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_question_1_text">
                            Question
                          </label>
                          
                          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" data-question-id= "1" name="question_1_text" id="id_question_1_text" type="text">
                        
                        </div>
        
                        <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
        
                          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_question_1_type">
                            Type of the question
                          </label>
        
                          <div class="relative">
        
                            <select class="question-type-select block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" data-question-id= "1" name="question_1_type" id="id_question_1_type">
                                <option value="text">Text</option>
                                <option value="number">Number</option>
                                <option value="date">Date</option>
                                <option value="radio">Radio</option>
                                <option value="checkbox">Checkbox</option>
                                <option value="select">Select</option>
                            </select>
        
                            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                              <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                            </div>
        
                          </div>
                          
                        </div>
        
                    </div>
        
                    <div class="p-4 hidden" id="question_1_choices_container">
                        <h4 class="text-gray-700 text-lg font-bold mb-2">Questions:</h4>
                        <div id="question_1_choices" class="p-4">
                            <div class="flex flex-wrap -mx-3 mb-2" id="question_1_choice_1">
        
                                <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                    
                                    <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" data-question-id= "1" data-choice-id="1" name="question_1_choice_1_text" id="id_question_1_choice_1_text" type="text" placeholder="Choice 1">
                    
                                </div>
                            
                            </div>

                            <div class="flex flex-wrap -mx-3 mb-2" id="question_1_choice_2">
        
                                <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                    
                                    <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" data-question-id= "1" data-choice-id="2" name="question_1_choice_2_text" id="id_question_1_choice_2_text" type="text" placeholder="Choice 2">
                    
                                </div>
                            
                            </div>
                        </div>
        
                        <p id="add_question_1_choice_button" data-question-id="1" class="add-choice-button text-blue-500 cursor-pointer">Add choice</p>
                    </div>
        
                </div>
                
            </div>

            <p id="add_question_button" class="text-blue-500 cursor-pointer">Add question</p>

            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Create my survey
            </button>
        </form>
        
    </div>
{% endblock content %}

{% block endScripts %}
<script src="{% static 'js/dashboard/createSurvey.js' %}"></script>
{% endblock endScripts %}

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Dashboard</h1>
                <p>Here you can see your recent activity.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2>Recent Posts</h2>
                <ul>
                    {% for post in posts %}
                        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>Recent Comments</h2>
                <ul>
                    {% for comment in comments %}
                        <li><a href="{{ comment.get_absolute_url }}">{{ comment.post.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/dashboard/mySurveys.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="container p-4">
        <div class="bg-white shadow-md rounded my-6">
          <table class="text-left w-full border-collapse">
            <thead>
              <tr>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Survey Name</th>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Survey Description</th>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Survey Link</th>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Survey Created</th>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Survey Updated</th>
                <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Responses</th>
              </tr>
            </thead>
            <tbody>
              {% for survey in surveys %}
              <tr class="hover:bg-grey-lighter">
                <td class="py-4 px-6 border-b border-grey-light">{{ survey.title }}</td>
                <td class="py-4 px-6 border-b border-grey-light">{{ survey.description }}</td>
                <td class="py-4 px-6 border-b border-grey-light"><a href="{% url 'surveys:passSurvey' survey.slug %}" class="text-blue-500">Link to survey</a></td>
                <td class="py-4 px-6 border-b border-grey-light">{{ survey.created_at }}</td>
                <td class="py-4 px-6 border-b border-grey-light">{{ survey.updated_at }}</td>
                <td class="py-4 px-6 border-b border-grey-light">
                  {% if survey.get_responses_count %}
                    <a href="{% url 'dashboard:surveyResponses' survey.slug %}" class="text-blue-500">Responses</a>
                  {% else %}
                    <p class="text-center">----</p>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
    </div>
{% endblock content %}

templates/dashboard/surveyResponse.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="container p-4">

        {% if statistics %}
          <h4 class="text-2xl font-bold mb-4">Statistics</h4>
          {% for statistic in statistics %}
            <h5 class="text-xl font-bold mb-4">{{ statistic.question }}</h5>
            <div class="bg-white shadow-md rounded my-6">
              {% if statistic.type == 'choices' %}
                <div class="chart-js-container hidden">
                  {% for answer in statistic.answers %}
                    <div class="chart-js hidden">{{ answer }}</div>
                  {% endfor %}
                </div>
                <canvas id="chart-{{statistic.question}}" class="w-1/12 p-6 chart_container"></canvas>
              {% else %}
                {% for answer in statistic.answers %}
                  <div class="py-4 px-6 border-b border-grey-light">{{ answer }}</div>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}
        {% endif %}

        {% for response in survey_response.get_responses %}
            <div class="bg-white shadow-md rounded my-6 p-4">
                <h5 class="text-xl font-bold">{{ response.question }}</h5>
                <div class="py-4 px-6">{{ response.answer }}</div>
            </div>
        {% endfor %}


    </div>
{% endblock content %}

templates/dashboard/surveyResponses.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="container p-4">
        <h1 class="text-2xl font-bold mb-4 text-red-500">Your survey has been submitted {{ survey.get_responses_count }} times!</h1>
        {% if survey.get_responses_count %}
          <div class="bg-white shadow-md rounded my-6">
              <table class="text-left w-full border-collapse">
                  <thead>
                    <tr>
                      <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Submition Date</th>
                      <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Answers</th> 
                    </tr>
                  </thead>
                  <tbody>
                    {% for survey_response in survey_responses %}
                    <tr class="hover:bg-grey-lighter">
                      <td class="py-4 px-6 border-b border-grey-light">{{ survey_response.created_at }}</td>
                      <td class="py-4 px-6 border-b border-grey-light"><a href="{% url 'dashboard:surveyResponse' survey.slug survey_response.id %}" class="text-blue-500">View</a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
              </table>
          </div>
        {% endif %}

        {% if statistics %}
          <h4 class="text-2xl font-bold mb-4 text-red-500">Statistics</h4>
          {% for statistic in statistics %}
            <h5 class="text-xl font-bold mb-4">{{ statistic.question }}</h5>
            <div class="bg-white shadow-md rounded my-6">
              {% if statistic.type == 'choices' %}
                <div class="chart-js-container hidden">
                  {% for answer in statistic.answers %}
                    <div class="chart-js hidden">{{ answer }}</div>
                  {% endfor %}
                </div>
                <canvas id="chart-{{statistic.question}}" class="w-1/12 p-6 chart_container"></canvas>
              {% else %}
                {% for answer in statistic.answers %}
                  <div class="py-4 px-6 border-b border-grey-light">{{ answer }}</div>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}
        {% endif %}


    </div>
{% endblock content %}

{% block endScripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script>

  let chart_containers = document.getElementsByClassName("chart_container");

  // For every chart container
  for (var i = 0; i < chart_containers.length; i++) {
    // Get the context of the canvas element we want to select
    // var dictionnary = document.getElementsByClassName("chart-js");
    var dictionnary = chart_containers[i].previousElementSibling.getElementsByClassName("chart-js");
    let data = [];
    let labels = [];

    // For every chart-js div
    for (var j = 0; j < dictionnary.length; j++) {
      // Get the data from the div
      var div_data = JSON.parse(dictionnary[j].innerHTML.split("'").join('"'));
      // append values to data array
      data.push(div_data.votes);
      // append labels to labels array
      labels.push(div_data.choice);
    }
    
    var chart_div = chart_containers[i].getContext('2d');
    // create a bar chart
    var myChart = new Chart(chart_div, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: 'Number of Votes',
          data: data,
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)'
          ],
          borderColor: [
            'rgba(255,99,132,1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero:true,
              stepSize: 1
            }
          }]
        }
      }
    });
  }




</script>
{% endblock endScripts %}